// Generated by CIRCT firtool-1.114.1
module scr1_pipe_ialu(
  input         clk,
                rst_n,
                exu2ialu_rvm_cmd_vd_i,
  output        ialu2exu_rvm_res_rdy_o,
  input  [31:0] exu2ialu_main_op1_i,
                exu2ialu_main_op2_i,
  input  [4:0]  exu2ialu_cmd_i,
  output [31:0] ialu2exu_main_res_o,
  output        ialu2exu_cmp_res_o,
  input  [31:0] exu2ialu_addr_op1_i,
                exu2ialu_addr_op2_i,
  output [31:0] ialu2exu_addr_res_o
);

  wire [32:0] mdu_sum_op2;
  wire [32:0] mdu_sum_op1;
  wire        mdu_sum_sub;
  wire [31:0] div_res_rem;
  wire        div_res_rem_c;
  wire        _mdu_cmd_mul_T = exu2ialu_cmd_i == 5'hF;
  wire        _mul_cmd_T_3 = exu2ialu_cmd_i == 5'h10;
  wire        _mul_cmd_T_1 = exu2ialu_cmd_i == 5'h11;
  wire        _mul_cmd_T_4 = exu2ialu_cmd_i == 5'h12;
  wire        _mdu_cmd_div_T = exu2ialu_cmd_i == 5'h13;
  wire        _div_cmd_T_4 = exu2ialu_cmd_i == 5'h14;
  wire        _div_cmd_T = exu2ialu_cmd_i == 5'h15;
  wire        _div_cmd_T_3 = exu2ialu_cmd_i == 5'h16;
  wire        isRvmCmd =
    _mdu_cmd_mul_T | _mul_cmd_T_3 | _mul_cmd_T_1 | _mul_cmd_T_4 | _mdu_cmd_div_T
    | _div_cmd_T_4 | _div_cmd_T | _div_cmd_T_3;
  wire        mdu_cmd_div = _mdu_cmd_div_T | _div_cmd_T_4 | _div_cmd_T | _div_cmd_T_3;
  wire        mdu_cmd_mul = _mdu_cmd_mul_T | _mul_cmd_T_4 | _mul_cmd_T_3 | _mul_cmd_T_1;
  wire        main_ops_diff_sgn = exu2ialu_main_op1_i[31] ^ exu2ialu_main_op2_i[31];
  reg  [1:0]  mdu_fsm_ff;
  wire        mdu_fsm_corr = mdu_fsm_ff == 2'h2;
  wire        _div_cmd_T_2 = _div_cmd_T | _div_cmd_T_3;
  wire        _div_cmd_T_5 = _div_cmd_T_3 | _div_cmd_T_4;
  wire        div_op1_is_neg = ~_div_cmd_T_5 & exu2ialu_main_op1_i[31];
  wire        _div_quo_bit_T = div_op1_is_neg ^ div_res_rem_c;
  wire        mdu_corr_req =
    mdu_cmd_div
    & ({_div_cmd_T_2, _div_cmd_T_5} == 2'h0 & main_ops_diff_sgn | _div_cmd_T_2
       & (|div_res_rem) & _div_quo_bit_T);
  reg  [31:0] mdu_iter_cnt;
  wire        mdu_iter_req =
    mdu_cmd_div & (|exu2ialu_main_op1_i) & (|exu2ialu_main_op2_i) & ~(|mdu_fsm_ff);
  wire [32:0] mdu_sum_res =
    mdu_sum_sub ? mdu_sum_op1 - mdu_sum_op2 : mdu_sum_op1 + mdu_sum_op2;
  reg         mdu_res_c_ff;
  reg  [31:0] mdu_res_hi_ff;
  reg  [31:0] mdu_res_lo_ff;
  wire        _GEN = mdu_fsm_ff == 2'h1;
  wire        _mul_cmd_T_2 = _mul_cmd_T_3 | _mul_cmd_T_1;
  wire        _mul_cmd_T_5 = _mul_cmd_T_3 | _mul_cmd_T_4;
  wire [32:0] mul_op1 =
    mdu_cmd_mul
      ? {~(_mul_cmd_T_2 & _mul_cmd_T_5) & exu2ialu_main_op1_i[31], exu2ialu_main_op1_i}
      : 33'h0;
  wire [32:0] mul_op2 =
    mdu_cmd_mul ? {~_mul_cmd_T_2 & exu2ialu_main_op2_i[31], exu2ialu_main_op2_i} : 33'h0;
  wire [63:0] mul_res =
    mdu_cmd_mul ? {{31{mul_op1[32]}}, mul_op1} * {{31{mul_op2[32]}}, mul_op2} : 64'h0;
  reg  [31:0] div_dvdnd_lo_ff;
  wire [32:0] div_dvdnd_lo_next =
    ~mdu_cmd_div | mdu_fsm_corr
      ? 33'h0
      : {(|mdu_fsm_ff) ? div_dvdnd_lo_ff : exu2ialu_main_op1_i, 1'h0};
  wire        _GEN_0 = mdu_cmd_div & mdu_fsm_ff != 2'h2;
  assign div_res_rem_c = _GEN_0 & mdu_sum_res[32];
  assign div_res_rem = _GEN_0 ? mdu_sum_res[31:0] : 32'h0;
  wire [31:0] _div_res_quo_T_3 =
    {(|mdu_fsm_ff) ? mdu_res_lo_ff[30:0] : 31'h0,
     _GEN_0
       & (~_div_quo_bit_T | div_op1_is_neg
          & {mdu_sum_res, div_dvdnd_lo_next[32:1]} == 65'h0)};
  wire        _GEN_1 = (mdu_cmd_div ? 2'h2 : {1'h0, mdu_cmd_mul}) == 2'h2;
  assign mdu_sum_sub =
    _GEN_1
    & (~_div_cmd_T_5 & main_ops_diff_sgn
       ^ ~(mdu_fsm_corr
             ? div_op1_is_neg ^ mdu_res_c_ff
             : (|mdu_fsm_ff) & ~(mdu_res_lo_ff[0])));
  assign mdu_sum_op1 =
    _GEN_1
      ? (mdu_fsm_corr
           ? {1'h0, mdu_res_hi_ff}
           : (|mdu_fsm_ff)
               ? {mdu_res_hi_ff, div_dvdnd_lo_ff[31]}
               : {{32{div_op1_is_neg}}, exu2ialu_main_op1_i[31]})
      : 33'h0;
  assign mdu_sum_op2 =
    _GEN_1 ? {~_div_cmd_T_5 & exu2ialu_main_op2_i[31], exu2ialu_main_op2_i} : 33'h0;
  wire        _GEN_2 = _mdu_cmd_mul_T | _mul_cmd_T_3 | _mul_cmd_T_1 | _mul_cmd_T_4;
  wire        _GEN_3 = _mdu_cmd_div_T | _div_cmd_T_4 | _div_cmd_T | _div_cmd_T_3;
  wire        _GEN_4 = mdu_fsm_ff == 2'h2;
  wire        rdy =
    _GEN_2 | _GEN_3
    & ((|mdu_fsm_ff) ? (_GEN ? mdu_iter_cnt[0] & ~mdu_corr_req : _GEN_4) : ~mdu_iter_req);
  wire        _GEN_5 = exu2ialu_cmd_i == 5'h0;
  wire        _GEN_6 = exu2ialu_cmd_i == 5'h1;
  wire        _GEN_7 = exu2ialu_cmd_i == 5'h2;
  wire        _GEN_8 = exu2ialu_cmd_i == 5'h3;
  wire        _GEN_9 = exu2ialu_cmd_i == 5'hC;
  wire [62:0] _result_T_26 =
    {{31{exu2ialu_main_op1_i[31]}}, exu2ialu_main_op1_i} << exu2ialu_main_op2_i[4:0];
  wire        _GEN_10 = exu2ialu_cmd_i == 5'hD;
  wire [31:0] _GEN_11 = {27'h0, exu2ialu_main_op2_i[4:0]};
  wire        _GEN_12 = exu2ialu_cmd_i == 5'hE;
  wire        _result_result_full_T_7 = exu2ialu_cmd_i == 5'h4;
  wire [32:0] _GEN_13 = {1'h0, exu2ialu_main_op1_i};
  wire [32:0] _GEN_14 = {1'h0, exu2ialu_main_op2_i};
  wire [32:0] result_result_full =
    _result_result_full_T_7 ? _GEN_13 + _GEN_14 : _GEN_13 - _GEN_14;
  wire        _GEN_15 = exu2ialu_cmd_i == 5'h5;
  wire [32:0] result_result_full_1 =
    _result_result_full_T_7 ? _GEN_13 + _GEN_14 : _GEN_13 - _GEN_14;
  wire        flags_zero =
    _result_result_full_T_7
      ? result_result_full[31:0] == 32'h0
      : result_result_full_1[31:0] == 32'h0;
  wire        flags_carry =
    _result_result_full_T_7 ? result_result_full[32] : result_result_full_1[32];
  wire        flags_overflow =
    _result_result_full_T_7
      ? exu2ialu_main_op1_i[31] & ~(exu2ialu_main_op2_i[31]) & ~(result_result_full[31])
        | ~(exu2ialu_main_op1_i[31]) & exu2ialu_main_op2_i[31] & result_result_full[31]
      : exu2ialu_main_op1_i[31] & ~(exu2ialu_main_op2_i[31]) & ~(result_result_full_1[31])
        | ~(exu2ialu_main_op1_i[31]) & exu2ialu_main_op2_i[31] & result_result_full_1[31];
  wire        flags_sign =
    _result_result_full_T_7 ? result_result_full[31] : result_result_full_1[31];
  wire        _GEN_16 = exu2ialu_cmd_i == 5'h6;
  wire        _cmp_res_T = flags_sign ^ flags_overflow;
  wire        _GEN_17 = exu2ialu_cmd_i == 5'h7;
  wire        _GEN_18 = exu2ialu_cmd_i == 5'h8;
  wire        _GEN_19 = exu2ialu_cmd_i == 5'h9;
  wire        _GEN_20 = exu2ialu_cmd_i == 5'hA;
  wire        _cmp_res_T_2 = flags_sign ^ flags_overflow;
  wire        _GEN_21 = exu2ialu_cmd_i == 5'hB;
  always @(posedge clk) begin
    automatic logic mdu_res_upd = exu2ialu_rvm_cmd_vd_i & ~rdy;
    if (~rst_n)
      mdu_fsm_ff <= 2'h0;
    else
      mdu_fsm_ff <=
        exu2ialu_rvm_cmd_vd_i
          ? ((|mdu_fsm_ff)
               ? (_GEN ? (mdu_iter_cnt[0] ? {mdu_corr_req, 1'h0} : 2'h1) : 2'h0)
               : {1'h0, mdu_iter_req})
          : 2'h0;
    if (exu2ialu_rvm_cmd_vd_i & ~rdy) begin
      if (|mdu_fsm_ff)
        mdu_iter_cnt <= {1'h0, mdu_iter_cnt[31:1]};
      else if (mdu_cmd_div)
        mdu_iter_cnt <= 32'h40000000;
    end
    if (mdu_res_upd & mdu_cmd_div)
      mdu_res_c_ff <= div_res_rem_c;
    if (mdu_res_upd) begin
      if (mdu_cmd_div) begin
        mdu_res_hi_ff <= div_res_rem;
        mdu_res_lo_ff <= _GEN_0 ? _div_res_quo_T_3 : 32'h0;
      end
      else if (mdu_cmd_mul) begin
        mdu_res_hi_ff <= mul_res[63:32];
        mdu_res_lo_ff <= mul_res[31:0];
      end
    end
    if (exu2ialu_rvm_cmd_vd_i & ~rdy)
      div_dvdnd_lo_ff <= div_dvdnd_lo_next[31:0];
  end // always @(posedge)
  assign ialu2exu_rvm_res_rdy_o = isRvmCmd & rdy;
  assign ialu2exu_main_res_o =
    isRvmCmd
      ? (_GEN_2
           ? ((|{_mul_cmd_T_2, _mul_cmd_T_5}) ? mul_res[63:32] : mul_res[31:0])
           : _GEN_3
               ? ((|mdu_fsm_ff)
                    ? (_GEN
                         ? (_GEN_0
                              ? (_div_cmd_T_2 ? mdu_sum_res[31:0] : _div_res_quo_T_3)
                              : 32'h0)
                         : _GEN_4
                             ? (_div_cmd_T_2 ? mdu_sum_res[31:0] : 32'h0 - mdu_res_lo_ff)
                             : 32'h0)
                    : (|exu2ialu_main_op2_i) | _div_cmd_T_2
                        ? exu2ialu_main_op1_i
                        : 32'hFFFFFFFF)
               : 32'h0)
      : _GEN_5
          ? 32'h0
          : _GEN_6
              ? exu2ialu_main_op1_i & exu2ialu_main_op2_i
              : _GEN_7
                  ? exu2ialu_main_op1_i | exu2ialu_main_op2_i
                  : _GEN_8
                      ? exu2ialu_main_op1_i ^ exu2ialu_main_op2_i
                      : _GEN_9
                          ? _result_T_26[31:0]
                          : _GEN_10
                              ? exu2ialu_main_op1_i >> _GEN_11
                              : _GEN_12
                                  ? $signed($signed(exu2ialu_main_op1_i) >>> _GEN_11)
                                  : _result_result_full_T_7
                                      ? result_result_full[31:0]
                                      : _GEN_15
                                          ? result_result_full_1[31:0]
                                          : _GEN_16
                                              ? {31'h0, _cmp_res_T}
                                              : _GEN_17
                                                  ? {31'h0, flags_carry}
                                                  : _GEN_18
                                                      ? {31'h0, flags_zero}
                                                      : _GEN_19
                                                          ? {31'h0, ~flags_zero}
                                                          : _GEN_20
                                                              ? {31'h0, ~_cmp_res_T_2}
                                                              : _GEN_21
                                                                  ? {31'h0, ~flags_carry}
                                                                  : 32'h0;
  assign ialu2exu_cmp_res_o =
    ~isRvmCmd
    & ~(_GEN_5 | _GEN_6 | _GEN_7 | _GEN_8 | _GEN_9 | _GEN_10 | _GEN_12
        | _result_result_full_T_7 | _GEN_15)
    & (_GEN_16
         ? _cmp_res_T
         : _GEN_17
             ? flags_carry
             : _GEN_18
                 ? flags_zero
                 : _GEN_19
                     ? ~flags_zero
                     : _GEN_20 ? ~_cmp_res_T_2 : _GEN_21 & ~flags_carry);
  assign ialu2exu_addr_res_o = exu2ialu_addr_op1_i + exu2ialu_addr_op2_i;
endmodule

