// Generated by CIRCT firtool-1.114.1
module IFUFSM(
  input  clock,
         reset,
         io_exu2ifu_pc_new_req_i,
         io_pipe2ifu_stop_fetch_i,
         io_imem_resp_er_discard_pnd,
  output io_ifu_fsm_fetch
);

  reg state_curr;
  always @(posedge clock) begin
    if (reset)
      state_curr <= 1'h0;
    else
      state_curr <=
        ~state_curr & io_exu2ifu_pc_new_req_i & ~io_pipe2ifu_stop_fetch_i
        | ~(state_curr
            & (io_pipe2ifu_stop_fetch_i | io_imem_resp_er_discard_pnd
               & ~io_exu2ifu_pc_new_req_i)) & state_curr;
  end // always @(posedge)
  assign io_ifu_fsm_fetch = state_curr;
endmodule

