// Generated by CIRCT firtool-1.114.1
module IMEM_cntr(
  input        clock,
               reset,
               io_imem_handshake_done,
               io_imem_resp_received,
  output       io_imem_pnd_txns_q_full,
  input        io_exu2ifu_pc_new_req_i,
               io_imem_resp_er_discard_pnd,
  output [2:0] io_imem_vd_pnd_txns_cnt,
  output       io_imem_resp_discard_req
);

  reg [2:0] imem_pnd_txns_cnt;
  reg [2:0] imem_resp_discard_cnt;
  always @(posedge clock) begin
    if (reset) begin
      imem_pnd_txns_cnt <= 3'h0;
      imem_resp_discard_cnt <= 3'h0;
    end
    else begin
      automatic logic [2:0] _GEN = {2'h0, io_imem_handshake_done};
      automatic logic [2:0] _imem_pnd_txns_cnt_next_T_4 =
        imem_pnd_txns_cnt + _GEN - {2'h0, io_imem_resp_received};
      imem_pnd_txns_cnt <= _imem_pnd_txns_cnt_next_T_4;
      imem_resp_discard_cnt <=
        io_exu2ifu_pc_new_req_i
          ? _imem_pnd_txns_cnt_next_T_4 - _GEN
          : io_imem_resp_er_discard_pnd
              ? _imem_pnd_txns_cnt_next_T_4
              : imem_resp_discard_cnt - 3'h1;
    end
  end // always @(posedge)
  assign io_imem_pnd_txns_q_full = &imem_pnd_txns_cnt;
  assign io_imem_vd_pnd_txns_cnt = imem_pnd_txns_cnt - imem_resp_discard_cnt;
  assign io_imem_resp_discard_req = |imem_resp_discard_cnt;
endmodule

