// Generated by CIRCT firtool-1.114.1
module InstrTypeFinder(
  input         clock,
                reset,
                io_instr_hi_rvi_lo_ff,
  input  [31:0] io_imem_rdata,
  input         io_exu2ifu_pc_new_req_i,
  input  [31:0] io_exu2ifu_pc_new_i,
  input         io_imem_resp_vd,
  output [2:0]  io_instr_type
);

  reg        new_pc_unaligned_ff;
  wire [1:0] _io_instr_type_T = {new_pc_unaligned_ff, io_instr_hi_rvi_lo_ff};
  wire [1:0] _io_instr_type_T_4 = {&(io_imem_rdata[17:16]), &(io_imem_rdata[1:0])};
  always @(posedge clock) begin
    if (reset)
      new_pc_unaligned_ff <= 1'h0;
    else if (io_exu2ifu_pc_new_req_i | io_imem_resp_vd)
      new_pc_unaligned_ff <= io_exu2ifu_pc_new_req_i & io_exu2ifu_pc_new_i[1];
  end // always @(posedge)
  assign io_instr_type =
    _io_instr_type_T == 2'h0
      ? {1'h0,
         (&{io_imem_rdata[17:16], io_imem_rdata[1:0]}) | _io_instr_type_T_4 == 2'h1
           ? 2'h1
           : {1'h1, _io_instr_type_T_4 == 2'h2}}
      : {1'h1, _io_instr_type_T != 2'h1, &(io_imem_rdata[17:16])};
endmodule

