// Generated by CIRCT firtool-1.114.1
module Instr_rvi_reg(
  input        clock,
               reset,
               io_imem_resp_vd,
  input  [2:0] io_instr_type,
  input        io_exu2ifu_pc_new_req_i,
  output       io_instr_hi_rvi_lo_ff
);

  reg instr_hi_rvi_lo_d;
  always @(posedge clock) begin
    if (reset)
      instr_hi_rvi_lo_d <= 1'h0;
    else
      instr_hi_rvi_lo_d <=
        ~io_exu2ifu_pc_new_req_i
        & (io_imem_resp_vd
             ? (&io_instr_type) | io_instr_type == 3'h5 | io_instr_type == 3'h3
             : instr_hi_rvi_lo_d);
  end // always @(posedge)
  assign io_instr_hi_rvi_lo_ff = instr_hi_rvi_lo_d;
endmodule

