// Generated by CIRCT firtool-1.114.1
module InstructionQueue(
  input        clock,
               reset,
               io_exu2ifu_pc_new_req_i,
               io_pipe2ifu_stop_fetch_i,
               io_ifu2idu_vd_o,
               io_idu2ifu_rdy_i,
               io_imem_resp_discard_req,
               io_imem_resp_ok,
  input  [2:0] io_instr_type,
  input        io_imem_resp_er,
  output       io_q_is_empty,
               io_q_has_free_slots,
               io_q_has_1_ocpd_hw,
  output [1:0] io_q_wr_size,
  input        io_q_rd_hword,
  output       io_q_flush_req,
  output [2:0] io_q_wptr,
               io_q_rptr,
  input  [2:0] io_imem_vd_pnd_txns_cnt
);

  wire [2:0] q_rptr_next;
  wire       io_q_flush_req_0 = io_exu2ifu_pc_new_req_i | io_pipe2ifu_stop_fetch_i;
  reg  [2:0] q_wptr;
  reg  [2:0] q_rptr;
  wire [2:0] _q_free_h_next_T_2 = 3'h4 - (q_wptr - q_rptr_next);
  wire       io_q_is_empty_0 = q_rptr == q_wptr;
  wire [1:0] q_rd_size =
    ~io_q_is_empty_0 & io_ifu2idu_vd_o & io_idu2ifu_rdy_i
      ? (io_q_rd_hword ? 2'h1 : 2'h2)
      : 2'h0;
  wire [1:0] q_wr_size =
    io_imem_resp_discard_req
      ? 2'h0
      : io_imem_resp_ok
          ? (io_instr_type == 3'h0
               ? 2'h0
               : io_instr_type == 3'h6 | (&io_instr_type) ? 2'h2 : 2'h1)
          : {1'h0, io_imem_resp_er};
  wire [2:0] _GEN = {io_q_flush_req_0, q_rd_size};
  wire [2:0] _q_rptr_next_T_2 = q_rptr + (io_q_rd_hword ? 3'h1 : 3'h2);
  assign q_rptr_next =
    (|_GEN)
      ? (io_q_flush_req_0 ? 3'h0 : (|q_rd_size) ? _q_rptr_next_T_2 : q_rptr)
      : q_rptr;
  always @(posedge clock) begin
    if (reset) begin
      q_wptr <= 3'h0;
      q_rptr <= 3'h0;
    end
    else begin
      if (|{io_q_flush_req_0, q_wr_size}) begin
        if (io_q_flush_req_0)
          q_wptr <= 3'h0;
        else if (|q_wr_size)
          q_wptr <= q_wptr + (q_wr_size == 2'h1 ? 3'h2 : 3'h1);
      end
      if (|_GEN) begin
        if (io_q_flush_req_0)
          q_rptr <= 3'h0;
        else if (|q_rd_size)
          q_rptr <= _q_rptr_next_T_2;
      end
    end
  end // always @(posedge)
  assign io_q_is_empty = io_q_is_empty_0;
  assign io_q_has_free_slots = {1'h0, _q_free_h_next_T_2[2:1]} > io_imem_vd_pnd_txns_cnt;
  assign io_q_has_1_ocpd_hw = q_wptr - q_rptr == 3'h1;
  assign io_q_wr_size = q_wr_size;
  assign io_q_flush_req = io_q_flush_req_0;
  assign io_q_wptr = q_wptr;
  assign io_q_rptr = q_rptr;
endmodule

