// Generated by CIRCT firtool-1.114.1
// VCS coverage exclude_file
module q_err_4x1(
  input  [1:0] R0_addr,
  input        R0_en,
               R0_clk,
  output       R0_data,
  input  [1:0] R1_addr,
  input        R1_en,
               R1_clk,
  output       R1_data,
  input  [1:0] W0_addr,
  input        W0_en,
               W0_clk,
               W0_data,
  input  [1:0] W1_addr,
  input        W1_en,
               W1_clk,
               W1_data,
  input  [1:0] W2_addr,
  input        W2_en,
               W2_clk,
               W2_data
);

  reg Memory[0:3];
  always @(posedge W0_clk) begin
    if (W0_en & 1'h1)
      Memory[W0_addr] <= W0_data;
    if (W1_en & 1'h1)
      Memory[W1_addr] <= W1_data;
    if (W2_en & 1'h1)
      Memory[W2_addr] <= W2_data;
  end // always @(posedge)
  assign R0_data = R0_en ? Memory[R0_addr] : 1'bx;
  assign R1_data = R1_en ? Memory[R1_addr] : 1'bx;
endmodule

