// Generated by CIRCT firtool-1.114.1
module scr1_pipe_ifu(
  input         rst_n,
                clk,
                pipe2ifu_stop_fetch_i,
                imem2ifu_req_ack_i,
  output        ifu2imem_req_o,
                ifu2imem_cmd_o,
  output [31:0] ifu2imem_addr_o,
  input  [31:0] imem2ifu_rdata_i,
  input  [1:0]  imem2ifu_resp_i,
  input         exu2ifu_pc_new_req_i,
  input  [31:0] exu2ifu_pc_new_i,
  input         idu2ifu_rdy_i,
  output [31:0] ifu2idu_instr_o,
  output        ifu2idu_imem_err_o,
                ifu2idu_err_rvi_hi_o,
                ifu2idu_vd_o
);

  scr1_pipe_ifu_4gen ifu_4gen (
    .clock                         (clk),
    .reset                         (~rst_n),
    .io_ctrl_pipe2ifu_stop_fetch_i (pipe2ifu_stop_fetch_i),
    .io_2Mem_imem2ifu_req_ack_i    (imem2ifu_req_ack_i),
    .io_2Mem_ifu2imem_req_o        (ifu2imem_req_o),
    .io_2Mem_ifu2imem_addr_o       (ifu2imem_addr_o),
    .io_2Mem_imem2ifu_rdata_i      (imem2ifu_rdata_i),
    .io_2Mem_imem2ifu_resp_i       (imem2ifu_resp_i),
    .io_2exu_exu2ifu_pc_new_req_i  (exu2ifu_pc_new_req_i),
    .io_2exu_exu2ifu_pc_new_i      (exu2ifu_pc_new_i),
    .io_2idu_idu2ifu_rdy_i         (idu2ifu_rdy_i),
    .io_2idu_ifu2idu_instr_o       (ifu2idu_instr_o),
    .io_2idu_ifu2idu_imem_err_o    (ifu2idu_imem_err_o),
    .io_2idu_ifu2idu_err_rvi_hi_o  (ifu2idu_err_rvi_hi_o),
    .io_2idu_ifu2idu_vd_o          (ifu2idu_vd_o)
  );
  assign ifu2imem_cmd_o = 1'h0;
endmodule

