// Generated by CIRCT firtool-1.114.1
module scr1_pipe_ifu_4gen(
  input         clock,
                reset,
                io_ctrl_pipe2ifu_stop_fetch_i,
                io_2Mem_imem2ifu_req_ack_i,
  output        io_2Mem_ifu2imem_req_o,
  output [31:0] io_2Mem_ifu2imem_addr_o,
  input  [31:0] io_2Mem_imem2ifu_rdata_i,
  input  [1:0]  io_2Mem_imem2ifu_resp_i,
  input         io_2exu_exu2ifu_pc_new_req_i,
  input  [31:0] io_2exu_exu2ifu_pc_new_i,
  input         io_2idu_idu2ifu_rdy_i,
  output [31:0] io_2idu_ifu2idu_instr_o,
  output        io_2idu_ifu2idu_imem_err_o,
                io_2idu_ifu2idu_err_rvi_hi_o,
                io_2idu_ifu2idu_vd_o
);

  wire        io_2Mem_ifu2imem_req_o_0;
  wire        _q_err_ext_R0_data;
  wire        _q_err_ext_R1_data;
  wire [15:0] _q_data_ext_R0_data;
  wire [15:0] _q_data_ext_R1_data;
  wire        _imemCntr_io_imem_pnd_txns_q_full;
  wire [2:0]  _imemCntr_io_imem_vd_pnd_txns_cnt;
  wire        _imemCntr_io_imem_resp_discard_req;
  wire        _instructionQueue_io_q_is_empty;
  wire        _instructionQueue_io_q_has_free_slots;
  wire        _instructionQueue_io_q_has_1_ocpd_hw;
  wire [1:0]  _instructionQueue_io_q_wr_size;
  wire        _instructionQueue_io_q_flush_req;
  wire [2:0]  _instructionQueue_io_q_wptr;
  wire [2:0]  _instructionQueue_io_q_rptr;
  wire        _ifuFSM_io_ifu_fsm_fetch;
  wire        _instrRviReg_io_instr_hi_rvi_lo_ff;
  wire [2:0]  _instrTypeFinder_io_instr_type;
  wire        imem_resp_er = io_2Mem_imem2ifu_resp_i == 2'h2;
  wire        imem_resp_ok = io_2Mem_imem2ifu_resp_i == 2'h1;
  wire        imem_resp_received = imem_resp_ok | imem_resp_er;
  wire        imem_resp_vd = imem_resp_received & ~_imemCntr_io_imem_resp_discard_req;
  wire        imem_resp_er_discard_pnd =
    imem_resp_er & ~_imemCntr_io_imem_resp_discard_req;
  wire        imem_handshake_done = io_2Mem_ifu2imem_req_o_0 & io_2Mem_imem2ifu_req_ack_i;
  wire        q_wr_en = imem_resp_vd & ~_instructionQueue_io_q_flush_req;
  wire        _GEN = _instructionQueue_io_q_wr_size == 2'h2;
  wire        _GEN_0 = q_wr_en & _GEN;
  wire        _GEN_1 = q_wr_en & ~_GEN & _instructionQueue_io_q_wr_size == 2'h1;
  wire [1:0]  _GEN_2 = _instructionQueue_io_q_wptr[1:0] + 2'h1;
  wire [1:0]  _q_err_next_T = _instructionQueue_io_q_rptr[1:0] + 2'h1;
  wire        q_rd_hword = ~(&(_q_data_ext_R1_data[1:0])) | _q_err_ext_R1_data;
  reg  [31:0] imem_addr_ff_full;
  wire [29:0] _GEN_3 = {29'h0, imem_handshake_done};
  assign io_2Mem_ifu2imem_req_o_0 =
    io_2exu_exu2ifu_pc_new_req_i & ~_imemCntr_io_imem_pnd_txns_q_full
    & ~io_ctrl_pipe2ifu_stop_fetch_i | _ifuFSM_io_ifu_fsm_fetch
    & ~_imemCntr_io_imem_pnd_txns_q_full & _instructionQueue_io_q_has_free_slots;
  wire        ifu2idu_vd_o =
    ~_instructionQueue_io_q_is_empty
    & (~_instructionQueue_io_q_has_1_ocpd_hw | q_rd_hword);
  always @(posedge clock) begin
    if (reset)
      imem_addr_ff_full <= 32'h0;
    else
      imem_addr_ff_full <=
        {imem_handshake_done | io_2exu_exu2ifu_pc_new_req_i
           ? (io_2exu_exu2ifu_pc_new_req_i
                ? io_2exu_exu2ifu_pc_new_i[31:2] + _GEN_3
                : (&(imem_addr_ff_full[5:2]))
                    ? imem_addr_ff_full[31:2] + _GEN_3
                    : {imem_addr_ff_full[31:6],
                       imem_addr_ff_full[5:2] + {3'h0, imem_handshake_done}})
           : imem_addr_ff_full[31:2],
         2'h0};
  end // always @(posedge)
  InstrTypeFinder instrTypeFinder (
    .clock                   (clock),
    .reset                   (reset),
    .io_instr_hi_rvi_lo_ff   (_instrRviReg_io_instr_hi_rvi_lo_ff),
    .io_imem_rdata           (io_2Mem_imem2ifu_rdata_i),
    .io_exu2ifu_pc_new_req_i (io_2exu_exu2ifu_pc_new_req_i),
    .io_exu2ifu_pc_new_i     (io_2exu_exu2ifu_pc_new_i),
    .io_imem_resp_vd         (imem_resp_vd),
    .io_instr_type           (_instrTypeFinder_io_instr_type)
  );
  Instr_rvi_reg instrRviReg (
    .clock                   (clock),
    .reset                   (reset),
    .io_imem_resp_vd         (imem_resp_vd),
    .io_instr_type           (_instrTypeFinder_io_instr_type),
    .io_exu2ifu_pc_new_req_i (io_2exu_exu2ifu_pc_new_req_i),
    .io_instr_hi_rvi_lo_ff   (_instrRviReg_io_instr_hi_rvi_lo_ff)
  );
  IFUFSM ifuFSM (
    .clock                       (clock),
    .reset                       (reset),
    .io_exu2ifu_pc_new_req_i     (io_2exu_exu2ifu_pc_new_req_i),
    .io_pipe2ifu_stop_fetch_i    (io_ctrl_pipe2ifu_stop_fetch_i),
    .io_imem_resp_er_discard_pnd (imem_resp_er_discard_pnd),
    .io_ifu_fsm_fetch            (_ifuFSM_io_ifu_fsm_fetch)
  );
  InstructionQueue instructionQueue (
    .clock                    (clock),
    .reset                    (reset),
    .io_exu2ifu_pc_new_req_i  (io_2exu_exu2ifu_pc_new_req_i),
    .io_pipe2ifu_stop_fetch_i (io_ctrl_pipe2ifu_stop_fetch_i),
    .io_ifu2idu_vd_o          (ifu2idu_vd_o),
    .io_idu2ifu_rdy_i         (io_2idu_idu2ifu_rdy_i),
    .io_imem_resp_discard_req (_imemCntr_io_imem_resp_discard_req),
    .io_imem_resp_ok          (imem_resp_ok),
    .io_instr_type            (_instrTypeFinder_io_instr_type),
    .io_imem_resp_er          (imem_resp_er),
    .io_q_is_empty            (_instructionQueue_io_q_is_empty),
    .io_q_has_free_slots      (_instructionQueue_io_q_has_free_slots),
    .io_q_has_1_ocpd_hw       (_instructionQueue_io_q_has_1_ocpd_hw),
    .io_q_wr_size             (_instructionQueue_io_q_wr_size),
    .io_q_rd_hword            (q_rd_hword),
    .io_q_flush_req           (_instructionQueue_io_q_flush_req),
    .io_q_wptr                (_instructionQueue_io_q_wptr),
    .io_q_rptr                (_instructionQueue_io_q_rptr),
    .io_imem_vd_pnd_txns_cnt  (_imemCntr_io_imem_vd_pnd_txns_cnt)
  );
  IMEM_cntr imemCntr (
    .clock                        (clock),
    .reset                        (reset),
    .io_imem_handshake_done       (imem_handshake_done),
    .io_imem_resp_received        (imem_resp_received),
    .io_imem_pnd_txns_q_full      (_imemCntr_io_imem_pnd_txns_q_full),
    .io_exu2ifu_pc_new_req_i      (io_2exu_exu2ifu_pc_new_req_i),
    .io_imem_resp_er_discard_pnd  (imem_resp_er_discard_pnd),
    .io_imem_vd_pnd_txns_cnt      (_imemCntr_io_imem_vd_pnd_txns_cnt),
    .io_imem_resp_discard_req     (_imemCntr_io_imem_resp_discard_req),
    .io_imem_resp_discard_cnt_upd
      (io_2exu_exu2ifu_pc_new_req_i | imem_resp_er | imem_resp_ok
       & _imemCntr_io_imem_resp_discard_req)
  );
  q_data_4x16 q_data_ext (
    .R0_addr (_q_err_next_T),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_q_data_ext_R0_data),
    .R1_addr (_instructionQueue_io_q_rptr[1:0]),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_q_data_ext_R1_data),
    .W0_addr (_GEN_2),
    .W0_en   (_GEN_1),
    .W0_clk  (clock),
    .W0_data (io_2Mem_imem2ifu_rdata_i[31:16]),
    .W1_addr (_instructionQueue_io_q_wptr[1:0]),
    .W1_en   (_GEN_1),
    .W1_clk  (clock),
    .W1_data (io_2Mem_imem2ifu_rdata_i[15:0]),
    .W2_addr (_instructionQueue_io_q_wptr[1:0]),
    .W2_en   (_GEN_0),
    .W2_clk  (clock),
    .W2_data (io_2Mem_imem2ifu_rdata_i[31:16])
  );
  q_err_4x1 q_err_ext (
    .R0_addr (_q_err_next_T),
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (_q_err_ext_R0_data),
    .R1_addr (_instructionQueue_io_q_rptr[1:0]),
    .R1_en   (1'h1),
    .R1_clk  (clock),
    .R1_data (_q_err_ext_R1_data),
    .W0_addr (_GEN_2),
    .W0_en   (_GEN_1),
    .W0_clk  (clock),
    .W0_data (imem_resp_er),
    .W1_addr (_instructionQueue_io_q_wptr[1:0]),
    .W1_en   (_GEN_1),
    .W1_clk  (clock),
    .W1_data (imem_resp_er),
    .W2_addr (_instructionQueue_io_q_wptr[1:0]),
    .W2_en   (_GEN_0),
    .W2_clk  (clock),
    .W2_data (imem_resp_er)
  );
  assign io_2Mem_ifu2imem_req_o = io_2Mem_ifu2imem_req_o_0;
  assign io_2Mem_ifu2imem_addr_o =
    {io_2exu_exu2ifu_pc_new_req_i
       ? io_2exu_exu2ifu_pc_new_i[31:2]
       : imem_addr_ff_full[31:2],
     2'h0};
  assign io_2idu_ifu2idu_instr_o =
    {(&(_q_data_ext_R1_data[1:0])) ? _q_data_ext_R0_data : 16'h0, _q_data_ext_R1_data};
  assign io_2idu_ifu2idu_imem_err_o =
    ~_instructionQueue_io_q_is_empty
    & (~_instructionQueue_io_q_has_1_ocpd_hw & (&(_q_data_ext_R1_data[1:0]))
       & _q_err_ext_R0_data | _q_err_ext_R1_data);
  assign io_2idu_ifu2idu_err_rvi_hi_o =
    ~_instructionQueue_io_q_is_empty & ~_instructionQueue_io_q_has_1_ocpd_hw
    & ~_q_err_ext_R1_data & (&(_q_data_ext_R1_data[1:0])) & _q_err_ext_R0_data;
  assign io_2idu_ifu2idu_vd_o = ifu2idu_vd_o;
endmodule

