// Generated by CIRCT firtool-1.114.1
module Mux_Variant_1(	// \\src\\main\\scala\\Main.scala:3:7
  input  [3:0] io_d0,	// \\src\\main\\scala\\Main.scala:4:14
               io_d1,	// \\src\\main\\scala\\Main.scala:4:14
               io_d2,	// \\src\\main\\scala\\Main.scala:4:14
               io_d3,	// \\src\\main\\scala\\Main.scala:4:14
  input  [1:0] io_sel,	// \\src\\main\\scala\\Main.scala:4:14
  output [3:0] io_y	// \\src\\main\\scala\\Main.scala:4:14
);

  assign io_y = io_sel[1] ? (io_sel[0] ? io_d3 : io_d2) : io_sel[0] ? io_d1 : io_d0;	// \\src\\main\\scala\\Main.scala:3:7, :14:{14,21,29,36}, :15:29
endmodule


// ----- 8< ----- FILE "verification�ver\layers-Mux_Variant_1-Verification-Cover.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.1
`include "verification\layers-Mux_Variant_1-Verification.sv"
`ifndef layers_Mux_Variant_1_Verification_Cover
`define layers_Mux_Variant_1_Verification_Cover	// <stdin>:12:5
`endif // layers_Mux_Variant_1_Verification_Cover	// <stdin>:12:5

// ----- 8< ----- FILE "verification�sume\layers-Mux_Variant_1-Verification-Assume.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.1
`include "verification\layers-Mux_Variant_1-Verification.sv"
`ifndef layers_Mux_Variant_1_Verification_Assume
`define layers_Mux_Variant_1_Verification_Assume	// <stdin>:11:5
`endif // layers_Mux_Variant_1_Verification_Assume	// <stdin>:11:5

// ----- 8< ----- FILE "verification�sert\layers-Mux_Variant_1-Verification-Assert.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.1
`include "verification\layers-Mux_Variant_1-Verification.sv"
`ifndef layers_Mux_Variant_1_Verification_Assert
`define layers_Mux_Variant_1_Verification_Assert	// <stdin>:10:5
`endif // layers_Mux_Variant_1_Verification_Assert	// <stdin>:10:5

// ----- 8< ----- FILE "verification\layers-Mux_Variant_1-Verification.sv" ----- 8< -----

// Generated by CIRCT firtool-1.114.1
`ifndef layers_Mux_Variant_1_Verification
`define layers_Mux_Variant_1_Verification	// <stdin>:9:3
`endif // layers_Mux_Variant_1_Verification	// <stdin>:9:3
